export const APP_SET_MODULE_TITLE = "APP_SET_MODULE_TITLE";

export const APP_FETCH_USERACCESS_INFO_REQUEST = "APP_FETCH_USERACCESS_INFO_REQUEST";
export const APP_FETCH_USERACCESS_INFO_SUCCESS = 'APP_FETCH_USERACCESS_INFO_SUCCESS';
export const APP_FETCH_USERACCESS_INFO_FAILURE = 'APP_FETCH_USERACCESS_INFO_FAILURE';
export const APP_INVALIDATE_USERACCESS = 'APP_INVALIDATE_USERACCESS';