export const KPI_FETCH_PERSON_TYPES_SUCCESS = "KPI_FETCH_PERSON_TYPES_SUCCESS";
export const KPI_FETCH_CONFIG_SUCCESS = "KPI_FETCH_CONFIG_SUCCESS";

export const KPI_FETCH_CHANNELS_REQUEST = "KPI_FETCH_CHANNELS_REQUEST";
export const KPI_FETCH_CHANNELS_SUCCESS = 'KPI_FETCH_CHANNELS_SUCCESS';
export const KPI_FETCH_CHANNELS_FAILURE = 'KPI_FETCH_CHANNELS_FAILURE';
export const KPI_INVALIDATE_CHANNELS = 'KPI_INVALIDATE_CHANNELS';

export const KPI_FETCH_GROUPS_REQUEST = "KPI_FETCH_GROUPS_REQUEST";
export const KPI_FETCH_GROUPS_SUCCESS = 'KPI_FETCH_GROUPS_SUCCESS';
export const KPI_FETCH_GROUPS_FAILURE = 'KPI_FETCH_GROUPS_FAILURE';
export const KPI_INVALIDATE_GROUPS = 'KPI_INVALIDATE_GROUPS';

export const KPI_FETCH_ATTRIBUTES_REQUEST = "KPI_FETCH_ATTRIBUTES_REQUEST";
export const KPI_FETCH_ATTRIBUTES_SUCCESS = 'KPI_FETCH_ATTRIBUTES_SUCCESS';
export const KPI_FETCH_ATTRIBUTES_FAILURE = 'KPI_FETCH_ATTRIBUTES_FAILURE';
export const KPI_INVALIDATE_ATTRIBUTES = 'KPI_INVALIDATE_ATTRIBUTES';