
// KPI ilə bağlı səlahiyyətlər
export const PRIV_KPI_RESULTS_MENU = "PRIV_KPI_RESULTS_MENU"; // Kpi nəticələri
export const PRIV_KPI_FAMILY_RESULTS_MENU = "PRIV_KPI_FAMILY_RESULTS_MENU"; // Ailə nəticələri
export const PRIV_KPI_RETURNS_MENU = "PRIV_KPI_RETURNS_MENU"; // Geriqaytarmalar

export const PRIV_KPIADMIN_MENU = "PRIV_KPIADMIN_MENU";
export const PRIV_KPIADMIN_MAIN_OPERATOR = "PRIV_KPIADMIN_MAIN_OPERATOR";
export const PRIV_KPIADMIN_ROUTE_OPERATOR = "PRIV_KPIADMIN_ROUTE_OPERATOR";
export const PRIV_KPIADMIN_AMB_OPERATOR = "PRIV_KPIADMIN_AMB_OPERATOR";
export const PRIV_KPIADMIN_MANAGER = "PRIV_KPIADMIN_MANAGER";

// Digər səlahiyyətlər
